export interface IInstruction {
  mnemonic: string;
  operands: Array<string>;
  opCode: number;
  size: number;
  flags: Array<string>;
}

const instructionList: Array<IInstruction> = [
  { mnemonic: 'NOP', operands: [], opCode: 0x00, size: 1, flags: [] },
  { mnemonic: 'LXI', operands: ['B', 'nn'], opCode: 0x01, size: 3, flags: [] },
  { mnemonic: 'STAX', operands: ['B'], opCode: 0x02, size: 1, flags: [] },
  { mnemonic: 'INX', operands: ['B'], opCode: 0x03, size: 1, flags: [] },
  { mnemonic: 'INR', operands: ['B'], opCode: 0x04, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'DCR', operands: ['B'], opCode: 0x05, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'MVI', operands: ['B', 'n'], opCode: 0x06, size: 2, flags: [] },
  { mnemonic: 'RLC', operands: [], opCode: 0x07, size: 1, flags: ['CY'] },
  { mnemonic: 'DAD', operands: ['B'], opCode: 0x09, size: 1, flags: ['CY'] },
  { mnemonic: 'LDAX', operands: ['B'], opCode: 0x0a, size: 1, flags: [] },
  { mnemonic: 'DCX', operands: ['B'], opCode: 0x0b, size: 1, flags: [] },
  { mnemonic: 'INR', operands: ['C'], opCode: 0x0c, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'DCR', operands: ['C'], opCode: 0x0d, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'MVI', operands: ['C', 'n'], opCode: 0x0e, size: 2, flags: [] },
  { mnemonic: 'RRC', operands: [], opCode: 0x0f, size: 1, flags: ['CY'] },
  { mnemonic: 'LXI', operands: ['D', 'nn'], opCode: 0x11, size: 3, flags: [] },
  { mnemonic: 'STAX', operands: ['D'], opCode: 0x12, size: 1, flags: [] },
  { mnemonic: 'INX', operands: ['D'], opCode: 0x13, size: 1, flags: [] },
  { mnemonic: 'INR', operands: ['D'], opCode: 0x14, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'DCR', operands: ['D'], opCode: 0x15, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'MVI', operands: ['D', 'n'], opCode: 0x16, size: 2, flags: [] },
  { mnemonic: 'RAL', operands: [], opCode: 0x17, size: 1, flags: ['CY'] },
  { mnemonic: 'DAD', operands: ['D'], opCode: 0x19, size: 1, flags: ['CY'] },
  { mnemonic: 'LDAX', operands: ['D'], opCode: 0x1a, size: 1, flags: [] },
  { mnemonic: 'DCX', operands: ['D'], opCode: 0x1b, size: 1, flags: [] },
  { mnemonic: 'INR', operands: ['E'], opCode: 0x1c, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'DCR', operands: ['E'], opCode: 0x1d, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'MVI', operands: ['E', 'n'], opCode: 0x1e, size: 2, flags: [] },
  { mnemonic: 'RAR', operands: [], opCode: 0x1f, size: 1, flags: ['CY'] },
  { mnemonic: 'LXI', operands: ['H', 'nn'], opCode: 0x21, size: 3, flags: [] },
  { mnemonic: 'SHLD', operands: ['a'], opCode: 0x22, size: 3, flags: [] },
  { mnemonic: 'INX', operands: ['H'], opCode: 0x23, size: 1, flags: [] },
  { mnemonic: 'INR', operands: ['H'], opCode: 0x24, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'DCR', operands: ['H'], opCode: 0x25, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'MVI', operands: ['H', 'n'], opCode: 0x26, size: 2, flags: [] },
  { mnemonic: 'DAA', operands: [], opCode: 0x27, size: 1, flags: [] },
  { mnemonic: 'DAD', operands: ['H'], opCode: 0x29, size: 1, flags: ['CY'] },
  { mnemonic: 'LHLD', operands: ['a'], opCode: 0x2a, size: 3, flags: [] },
  { mnemonic: 'DCX', operands: ['H'], opCode: 0x2b, size: 1, flags: [] },
  { mnemonic: 'INR', operands: ['L'], opCode: 0x2c, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'DCR', operands: ['L'], opCode: 0x2d, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'MVI', operands: ['L', 'n'], opCode: 0x2e, size: 2, flags: [] },
  { mnemonic: 'CMA', operands: [], opCode: 0x2f, size: 1, flags: [] },
  { mnemonic: 'LXI', operands: ['SP', 'nn'], opCode: 0x31, size: 3, flags: [] },
  { mnemonic: 'STA', operands: ['a'], opCode: 0x32, size: 3, flags: [] },
  { mnemonic: 'INX', operands: ['SP'], opCode: 0x33, size: 1, flags: [] },
  { mnemonic: 'INR', operands: ['M'], opCode: 0x34, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'DCR', operands: ['M'], opCode: 0x35, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'MVI', operands: ['M', 'n'], opCode: 0x36, size: 2, flags: [] },
  { mnemonic: 'STC', operands: [], opCode: 0x37, size: 1, flags: ['CY'] },
  { mnemonic: 'DAD', operands: ['SP'], opCode: 0x39, size: 1, flags: ['CY'] },
  { mnemonic: 'LDA', operands: ['a'], opCode: 0x3a, size: 3, flags: [] },
  { mnemonic: 'DCX', operands: ['SP'], opCode: 0x3b, size: 1, flags: [] },
  { mnemonic: 'INR', operands: ['A'], opCode: 0x3c, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'DCR', operands: ['A'], opCode: 0x3d, size: 1, flags: ['Z', 'S', 'P', 'AC'] },
  { mnemonic: 'MVI', operands: ['A', 'n'], opCode: 0x3e, size: 2, flags: [] },
  { mnemonic: 'CMC', operands: [], opCode: 0x3f, size: 1, flags: ['CY'] },
  { mnemonic: 'MOV', operands: ['B', 'B'], opCode: 0x40, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['B', 'C'], opCode: 0x41, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['B', 'D'], opCode: 0x42, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['B', 'E'], opCode: 0x43, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['B', 'H'], opCode: 0x44, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['B', 'L'], opCode: 0x45, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['B', 'M'], opCode: 0x46, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['B', 'A'], opCode: 0x47, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['C', 'B'], opCode: 0x48, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['C', 'C'], opCode: 0x49, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['C', 'D'], opCode: 0x4a, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['C', 'E'], opCode: 0x4b, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['C', 'H'], opCode: 0x4c, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['C', 'L'], opCode: 0x4d, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['C', 'M'], opCode: 0x4e, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['C', 'A'], opCode: 0x4f, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['D', 'B'], opCode: 0x50, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['D', 'C'], opCode: 0x51, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['D', 'D'], opCode: 0x52, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['D', 'E'], opCode: 0x53, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['D', 'H'], opCode: 0x54, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['D', 'L'], opCode: 0x55, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['D', 'M'], opCode: 0x56, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['D', 'A'], opCode: 0x57, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['E', 'B'], opCode: 0x58, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['E', 'C'], opCode: 0x59, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['E', 'D'], opCode: 0x5a, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['E', 'E'], opCode: 0x5b, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['E', 'H'], opCode: 0x5c, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['E', 'L'], opCode: 0x5d, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['E', 'M'], opCode: 0x5e, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['E', 'A'], opCode: 0x5f, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['H', 'B'], opCode: 0x60, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['H', 'C'], opCode: 0x61, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['H', 'D'], opCode: 0x62, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['H', 'E'], opCode: 0x63, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['H', 'H'], opCode: 0x64, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['H', 'L'], opCode: 0x65, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['H', 'M'], opCode: 0x66, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['H', 'A'], opCode: 0x67, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['L', 'B'], opCode: 0x68, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['L', 'C'], opCode: 0x69, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['L', 'D'], opCode: 0x6a, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['L', 'E'], opCode: 0x6b, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['L', 'H'], opCode: 0x6c, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['L', 'L'], opCode: 0x6d, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['L', 'M'], opCode: 0x6e, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['L', 'A'], opCode: 0x6f, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['M', 'B'], opCode: 0x70, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['M', 'C'], opCode: 0x71, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['M', 'D'], opCode: 0x72, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['M', 'E'], opCode: 0x73, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['M', 'H'], opCode: 0x74, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['M', 'L'], opCode: 0x75, size: 1, flags: [] },
  { mnemonic: 'HLT', operands: [], opCode: 0x76, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['M', 'A'], opCode: 0x77, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['A', 'B'], opCode: 0x78, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['A', 'C'], opCode: 0x79, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['A', 'D'], opCode: 0x7a, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['A', 'E'], opCode: 0x7b, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['A', 'H'], opCode: 0x7c, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['A', 'L'], opCode: 0x7d, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['A', 'M'], opCode: 0x7e, size: 1, flags: [] },
  { mnemonic: 'MOV', operands: ['A', 'A'], opCode: 0x7f, size: 1, flags: [] },
  { mnemonic: 'ADD', operands: ['B'], opCode: 0x80, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADD', operands: ['C'], opCode: 0x81, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADD', operands: ['D'], opCode: 0x82, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADD', operands: ['E'], opCode: 0x83, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADD', operands: ['H'], opCode: 0x84, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADD', operands: ['L'], opCode: 0x85, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADD', operands: ['M'], opCode: 0x86, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADD', operands: ['A'], opCode: 0x87, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADC', operands: ['B'], opCode: 0x88, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADC', operands: ['C'], opCode: 0x89, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADC', operands: ['D'], opCode: 0x8a, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADC', operands: ['E'], opCode: 0x8b, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADC', operands: ['H'], opCode: 0x8c, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADC', operands: ['L'], opCode: 0x8d, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADC', operands: ['M'], opCode: 0x8e, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ADC', operands: ['A'], opCode: 0x8f, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SUB', operands: ['B'], opCode: 0x90, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SUB', operands: ['C'], opCode: 0x91, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SUB', operands: ['D'], opCode: 0x92, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SUB', operands: ['E'], opCode: 0x93, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SUB', operands: ['H'], opCode: 0x94, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SUB', operands: ['L'], opCode: 0x95, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SUB', operands: ['M'], opCode: 0x96, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SUB', operands: ['A'], opCode: 0x97, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SBB', operands: ['B'], opCode: 0x98, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SBB', operands: ['C'], opCode: 0x99, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SBB', operands: ['D'], opCode: 0x9a, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SBB', operands: ['E'], opCode: 0x9b, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SBB', operands: ['H'], opCode: 0x9c, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SBB', operands: ['L'], opCode: 0x9d, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SBB', operands: ['M'], opCode: 0x9e, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'SBB', operands: ['A'], opCode: 0x9f, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ANA', operands: ['B'], opCode: 0xa0, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ANA', operands: ['C'], opCode: 0xa1, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ANA', operands: ['D'], opCode: 0xa2, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ANA', operands: ['E'], opCode: 0xa3, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ANA', operands: ['H'], opCode: 0xa4, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ANA', operands: ['L'], opCode: 0xa5, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ANA', operands: ['M'], opCode: 0xa6, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ANA', operands: ['A'], opCode: 0xa7, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'XRA', operands: ['B'], opCode: 0xa8, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'XRA', operands: ['C'], opCode: 0xa9, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'XRA', operands: ['D'], opCode: 0xaa, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'XRA', operands: ['E'], opCode: 0xab, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'XRA', operands: ['H'], opCode: 0xac, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'XRA', operands: ['L'], opCode: 0xad, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'XRA', operands: ['M'], opCode: 0xae, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'XRA', operands: ['A'], opCode: 0xaf, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ORA', operands: ['B'], opCode: 0xb0, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ORA', operands: ['C'], opCode: 0xb1, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ORA', operands: ['D'], opCode: 0xb2, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ORA', operands: ['E'], opCode: 0xb3, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ORA', operands: ['H'], opCode: 0xb4, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ORA', operands: ['L'], opCode: 0xb5, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ORA', operands: ['M'], opCode: 0xb6, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'ORA', operands: ['A'], opCode: 0xb7, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'CMP', operands: ['B'], opCode: 0xb8, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'CMP', operands: ['C'], opCode: 0xb9, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'CMP', operands: ['D'], opCode: 0xba, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'CMP', operands: ['E'], opCode: 0xbb, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'CMP', operands: ['H'], opCode: 0xbc, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'CMP', operands: ['L'], opCode: 0xbd, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'CMP', operands: ['M'], opCode: 0xbe, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'CMP', operands: ['A'], opCode: 0xbf, size: 1, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'RNZ', operands: [], opCode: 0xc0, size: 1, flags: [] },
  { mnemonic: 'POP', operands: ['B'], opCode: 0xc1, size: 1, flags: [] },
  { mnemonic: 'JNZ', operands: ['a'], opCode: 0xc2, size: 3, flags: [] },
  { mnemonic: 'JMP', operands: ['a'], opCode: 0xc3, size: 3, flags: [] },
  { mnemonic: 'CNZ', operands: ['a'], opCode: 0xc4, size: 3, flags: [] },
  { mnemonic: 'PUSH', operands: ['B'], opCode: 0xc5, size: 1, flags: [] },
  { mnemonic: 'ADI', operands: ['n'], opCode: 0xc6, size: 2, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'RST', operands: ['0'], opCode: 0xc7, size: 1, flags: [] },
  { mnemonic: 'RZ', operands: [], opCode: 0xc8, size: 1, flags: [] },
  { mnemonic: 'RET', operands: [], opCode: 0xc9, size: 1, flags: [] },
  { mnemonic: 'JZ', operands: ['a'], opCode: 0xca, size: 3, flags: [] },
  { mnemonic: 'CZ', operands: ['a'], opCode: 0xcc, size: 3, flags: [] },
  { mnemonic: 'CALL', operands: ['a'], opCode: 0xcd, size: 3, flags: [] },
  { mnemonic: 'ACI', operands: ['n'], opCode: 0xce, size: 2, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'RST', operands: ['1'], opCode: 0xcf, size: 1, flags: [] },
  { mnemonic: 'RNC', operands: [], opCode: 0xd0, size: 1, flags: [] },
  { mnemonic: 'POP', operands: ['D'], opCode: 0xd1, size: 1, flags: [] },
  { mnemonic: 'JNC', operands: ['a'], opCode: 0xd2, size: 3, flags: [] },
  { mnemonic: 'OUT', operands: ['n'], opCode: 0xd3, size: 2, flags: [] },
  { mnemonic: 'CNC', operands: ['a'], opCode: 0xd4, size: 2, flags: [] },
  { mnemonic: 'PUSH', operands: ['D'], opCode: 0xd5, size: 1, flags: [] },
  { mnemonic: 'SUI', operands: ['n'], opCode: 0xd6, size: 2, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'RST', operands: ['2'], opCode: 0xd7, size: 1, flags: [] },
  { mnemonic: 'RC', operands: [], opCode: 0xd8, size: 1, flags: [] },
  { mnemonic: 'JC', operands: ['a'], opCode: 0xda, size: 3, flags: [] },
  { mnemonic: 'IN', operands: ['n'], opCode: 0xdb, size: 2, flags: [] },
  { mnemonic: 'CC', operands: ['a'], opCode: 0xdc, size: 3, flags: [] },
  { mnemonic: 'SBI', operands: ['n'], opCode: 0xde, size: 2, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'RST', operands: ['3'], opCode: 0xdf, size: 1, flags: [] },
  { mnemonic: 'RPO', operands: [], opCode: 0xe0, size: 1, flags: [] },
  { mnemonic: 'POP', operands: ['H'], opCode: 0xe1, size: 1, flags: [] },
  { mnemonic: 'JPO', operands: ['a'], opCode: 0xe2, size: 3, flags: [] },
  { mnemonic: 'XTHL', operands: [], opCode: 0xe3, size: 1, flags: [] },
  { mnemonic: 'CPO', operands: ['a'], opCode: 0xe4, size: 3, flags: [] },
  { mnemonic: 'PUSH', operands: ['H'], opCode: 0xe5, size: 1, flags: [] },
  { mnemonic: 'ANI', operands: ['n'], opCode: 0xe6, size: 2, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'RST', operands: ['4'], opCode: 0xe7, size: 1, flags: [] },
  { mnemonic: 'RPE', operands: [], opCode: 0xe8, size: 1, flags: [] },
  { mnemonic: 'PCHL', operands: [], opCode: 0xe9, size: 1, flags: [] },
  { mnemonic: 'JPE', operands: ['a'], opCode: 0xea, size: 3, flags: [] },
  { mnemonic: 'XCHG', operands: [], opCode: 0xeb, size: 1, flags: [] },
  { mnemonic: 'CPE', operands: ['a'], opCode: 0xec, size: 3, flags: [] },
  { mnemonic: 'XRI', operands: ['n'], opCode: 0xee, size: 2, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'RST', operands: ['5'], opCode: 0xef, size: 1, flags: [] },
  { mnemonic: 'RP', operands: [], opCode: 0xf0, size: 1, flags: [] },
  { mnemonic: 'POP', operands: ['PSW'], opCode: 0xf1, size: 1, flags: [] },
  { mnemonic: 'JP', operands: ['a'], opCode: 0xf2, size: 3, flags: [] },
  { mnemonic: 'DI', operands: [], opCode: 0xf3, size: 1, flags: [] },
  { mnemonic: 'CP', operands: ['a'], opCode: 0xf4, size: 3, flags: [] },
  { mnemonic: 'PUSH', operands: ['PSW'], opCode: 0xf5, size: 1, flags: [] },
  { mnemonic: 'ORI', operands: ['n'], opCode: 0xf6, size: 2, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'RST', operands: ['6'], opCode: 0xf7, size: 1, flags: [] },
  { mnemonic: 'RM', operands: [], opCode: 0xf8, size: 1, flags: [] },
  { mnemonic: 'SPHL', operands: [], opCode: 0xf9, size: 1, flags: [] },
  { mnemonic: 'JM', operands: ['a'], opCode: 0xfa, size: 3, flags: [] },
  { mnemonic: 'EI', operands: [], opCode: 0xfb, size: 1, flags: [] },
  { mnemonic: 'CM', operands: ['a'], opCode: 0xfc, size: 3, flags: [] },
  { mnemonic: 'CPI', operands: ['n'], opCode: 0xfe, size: 2, flags: ['Z', 'S', 'P', 'CY', 'AC'] },
  { mnemonic: 'RST', operands: ['7'], opCode: 0xff, size: 1, flags: [] }
];

export default instructionList;
